# Πρόλογος δεύτερης έκδοσης {.unnumbered}

Καλώς ήρθατε στη δεύτερη έκδοση του βιβλίου "Η R για την Επιστήμη των Δεδομένων"!
Πρόκειται για μία μεγάλης κλίμακας επανεπεξεργασία της πρώτης έκδοσης, αφαιρώντας υλικό που δεν θεωρούμε πλέον χρήσιμο, προσθέτοντας υλικό που θα θέλαμε να είχαμε συμπεριλάβει στην πρώτη έκδοση και γενικά ανανεώνοντας το κείμενο και τον κώδικα για να αντικατοπτρίζουν αλλαγές στις καλές πρακτικές.
Είμαστε επίσης ιδιαίτερα ενθουσιασμένοι που καλωσορίζουμε μία νέα συν-συγγραφέα: την Mine Çetinkaya-Rundel, μία διακεκριμένη εκπαιδευτικό στην επιστήμη των δεδομένων και μία από τους συναδέλφους μας στην Posit (την εταιρεία που ήταν παλαιότερα γνωστή ως RStudio).

Ακολουθεί μία σύντομη περίληψη των μεγαλύτερων αλλαγών:

-   Το πρώτο μέρος του βιβλίου μετονομάστηκε σε "Η ολοκληρωμένη εικόνα".
    Ο στόχος αυτής της ενότητας είναι να σας δώσει την ευρύτερη εικόνα της επιστήμης των δεδομένων προτού εμβαθύνουμε σε λεπτομέρειες.

-   Το δεύτερο μέρος του βιβλίου ονομάζεται «Οπτικοποίηση».
    Αυτό το μέρος παρέχει μία πιο εμπεριστατωμένη κάλυψη των εργαλείων οπτικοποίησης των δεδομένων και των αντίστοιχων καλών πρακτικών, σε σύγκριση με την πρώτη έκδοση.
    Το καλύτερο μέρος όπου θα βρείτε όλες τις σχετικές λεπτομέρειες εξακολουθεί να είναι το [βιβλίο της ggplot2](http://ggplot2-book.org/), πλέον όμως το βιβλίο καλύπτει περισσότερες από τις πιο σημαντικές τεχνικές.

-   Το τρίτο μέρος του βιβλίου ονομάζεται πλέον "Μετασχηματισμοί" και περιλαμβάνει νέα κεφάλαια σχετικά με αριθμούς, λογικά διανύσματα και κενές τιμές.
    Αυτά ήταν προηγουμένως μέρη του κεφαλαίου του μετασχηματισμού δεδομένων, για να καλυφθούν όλες οι λεπτομέρειες όμως χρειάζονταν πολύ περισσότερος χώρος.

-   Το τέταρτο μέρος του βιβλίου ονομάζεται «Εισαγωγή δεδομένων».
    Πρόκειται για ένα νέο σύνολο κεφαλαίων που εκτείνεται πέρα από την ανάγνωση απλών αρχείων κειμένων όπως στην εργασία με υπολογιστικά φύλλα, τη λήψη δεδομένων από βάσεις δεδομένων, την εργασία με δεδομένα μεγάλου όγκου (big data), την ορθογωνοποίηση ιεραρχικών δεδομένων και την ιστοσυγκομιδή, την συγκομιδή δεδομένων από ιστοσελίδες.

-   Το μέρος "Προγραμματισμός" παραμένει, αλλά έχει ξαναγραφτεί από την αρχή έτσι ώστε να εστιάσει στα πιο σημαντικά μέρη της δημιουργίας συναρτήσεων και των δομών επανάληψης.
    Η δημιουργία συναρτήσεων περιλαμβάνει πλέον λεπτομέρειες σχετικά με τον τρόπο περιτύλιξης (wrapping) των συναρτήσεων του tidyverse (αντιμετώπιση των προκλήσεων που προκύπτουν από τον τρόπο που οι tidy συναρτήσεις αξιολογούν τα ορίσματα), καθώς αυτό έχει γίνει πολύ πιο εύκολο και σημαντικό τα τελευταία χρόνια.
    Έχουμε ακόμη προσθέσει ένα νέο κεφάλαιο με σημαντικές συναρτήσεις του βασικού συνόλου λειτουργιών της R που είναι πιθανό να συναντήσετε εκεί έξω.

-   Το μέρος της μοντελοποίησης έχει αφαιρεθεί.
    Ποτέ δεν είχαμε αρκετό χώρο για να αποδώσουμε πλήρως τη μοντελοποίηση και πλέον υπάρχουν πολύ καλύτεροι διαθέσιμοι πόροι.
    Γενικά συνιστούμε να χρησιμοποιήσετε τα πακέτα [tidymodels](https://www.tidymodels.org/), καθώς και να διαβάσετε το [Tidy Modeling with R](https://www.tmwr.org/) των Max Kuhn και Julia Silge.

-   Το μέρος "Επικοινωνία" παραμένει, αλλά έχει ενημερωθεί διεξοδικά έτσι ώστε να περιλαμβάνει το [Quarto](https://quarto.org/) στη θέση του R Markdown.
    Αυτή η έκδοση του βιβλίου έχει γραφτεί σε Quarto, το ξεκάθαρο εργαλείο του μέλλοντος.
