on:
  push:
    branches:
      - develop
  pull_request:
    branches:
      - develop
  schedule:
    # run every day at 11 PM
    - cron: '0 23 * * *'


name: Quarto Publish

jobs:
  build-deploy:
    runs-on: ubuntu-latest
    env:
      GITHUB_PAT: ${{ secrets.GITHUB_TOKEN }}
    steps:
      - name: Check out repository
        uses: actions/checkout@v4

      - name: Set up Quarto
        uses: quarto-dev/quarto-actions/setup@v2

      - name: Render book to all format
        # Add any command line argument needed
        run: |
          quarto render

      - name: Deploy to GitHub pages
        if: github.event_name != 'pull_request'
        uses: JamesIves/github-pages-deploy-action@4.6.0
        with:
          branch: gh-pages
          folder: _book
